app = "ebay-search-app"
primary_region = "ord"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3023
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
